MovieStore/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MovieStore.Models;
using Microsoft.AspNet.Identity;

namespace MovieStore.Controllers
{
    public class CustomersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Customers
        [Authorize(Roles ="Admin")]
        public ActionResult Index() { 
                
            return View(db.Customers.ToList());
        }

        // GET: Customers/Details/5
        [Authorize(Roles = "Admin")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        public ActionResult CheckOut(int? CustomerId)
        {
            if (Session["OrderId"] == null)
            {
                return RedirectToAction("ShopMovies", "Movies");
            }
            Order order = new Order();
            if (User.Identity.IsAuthenticated)
            {
                int orderId = Convert.ToInt32(Session["OrderId"]);
                string UserId= User.Identity.GetUserId();
                order = db.Orders.Find(orderId);
                order.CustomerId = UserId;
                order.OrderDate = DateTime.Now;

                db.Entry(order).State = EntityState.Modified;
                db.SaveChanges();

                CheckOutStatus(orderId);
            }
            else
            {
                int orderId = Convert.ToInt32(Session["OrderId"]);
                order = db.Orders.Find(orderId);
                order.CustomerId = CustomerId.ToString();
                order.OrderDate = DateTime.Now;

                db.Entry(order).State = EntityState.Modified;
                db.SaveChanges();

                CheckOutStatus(orderId);
            }



            Session["OrderId"] = null;
            return View(order);
        }

        public ActionResult CheckOutStatus(int? OrderId)
        {

            return View();
        }
        // GET: Customers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Customers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Firstname,Lastname,BillingAddress,BillingZip,BillingCity,EmailAddress,Phone")] Customer customer)
        {
            if (ModelState.IsValid)
            {
                db.Customers.Add(customer);
                db.SaveChanges();
                CheckOut(customer.Id);
                return RedirectToAction("Index","Movies");
            }

            return View(customer);
        }

        // GET: Customers/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // POST: Customers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Firstname,Lastname,BillingAddress,BillingZip,BillingCity,EmailAddress,Phone")] Customer customer)
        {
            if (ModelState.IsValid)
            {
                db.Entry(customer).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(customer);
        }

        // GET: Customers/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // POST: Customers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Customer customer = db.Customers.Find(id);
            db.Customers.Remove(customer);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MovieStore/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MovieStore.Models;
using MovieStore.Models.ViewModels;
using System.Web.SessionState;
using PagedList;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;

namespace MovieStore.Controllers
{
    public class OrdersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private ApplicationUserManager _userManager;
        public OrdersController() { }
        public OrdersController(ApplicationUserManager userManager)
        {
            UserManager = userManager;
        }
        private ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            set
            {
                _userManager = value;
            }
        }
        // GET: Orders
        [Authorize]
        public ActionResult Index(int? page)
        {
            int currentPageIndex = page.HasValue ? page.Value : 1;

            var orders = db.Orders.ToList();
            orders.OrderByDescending(obj => obj.Id);


            return View(orders.ToPagedList(currentPageIndex, 10));
            //return View(db.Orders.ToList());
        }

        public ActionResult DisplayUserName(string id)
        {
            Models.ViewModels.UserViewModel userViewModel = new Models.ViewModels.UserViewModel();
            var user=UserManager.FindById(id);
            if (user != null)
            {
                userViewModel.FirstName = user.FirstName;
            }else
            {
                int intId = Convert.ToInt32(id);
                Customer customer = db.Customers.Find(intId);
                if (customer != null)
                {
                    userViewModel.FirstName = customer.Firstname;
                }
                else
                {
                    userViewModel.FirstName = "";
                }
                
                
            }
            
            return PartialView(userViewModel);
        }
        [Authorize]
        public ActionResult PreviousOrder(int? page)
        {
            string UserId= User.Identity.GetUserId();
            int currentPageIndex = page.HasValue ? page.Value : 1;
                var orders = db.Orders.Where(obj=>obj.CustomerId== UserId).ToList();
            orders.OrderByDescending(obj => obj.Id);


            return View(orders.ToPagedList(currentPageIndex, 10));
            //return View(db.Orders.ToList());
        }

        [Authorize]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        // GET: Orders/Create
        [Authorize(Roles ="Admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Orders/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles ="Admin")]
        public ActionResult Create([Bind(Include = "Id,OrderDate,Customer_id")] Order order)
        {
            if (ModelState.IsValid)
            {
                db.Orders.Add(order);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(order);
        }

        // GET: Orders/Edit/5
        [Authorize(Roles ="Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        // POST: Orders/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles ="Admin")]
        public ActionResult Edit([Bind(Include = "Id,OrderDate,Customer_id")] Order order)
        {
            if (ModelState.IsValid)
            {
                db.Entry(order).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(order);
        }

        // GET: Orders/Delete/5
        [Authorize(Roles ="Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        // POST: Orders/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        [Authorize(Roles ="Admin")]
        public ActionResult DeleteConfirmed(int id)
        {
            Order order = db.Orders.Find(id);
            try
            {
                db.Orders.Remove(order);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {

                throw new Exception(ex.Message);
            }
            
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MovieStore/Controllers/RoleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using static MovieStore.ApplicationSignInManager;
using Microsoft.AspNet.Identity.Owin;
using MovieStore.Models;
using System.Threading.Tasks;
using System.Web.Security;


namespace MovieStore.Controllers
{
    [Authorize(Roles = "Admin")]
    public class RoleController : Controller
    {

        private ApplicationRoleManager _roleManager;
        private ApplicationUserManager _userManager;

        public RoleController()
        {
        }

        public RoleController(ApplicationRoleManager roleManager, ApplicationUserManager userManager
            )
        {
            RoleManager = roleManager;
            UserManager = userManager;



        }



        public ApplicationRoleManager RoleManager
        {
            get
            {
                return _roleManager ?? HttpContext.GetOwinContext().Get<ApplicationRoleManager>();
            }
            private set
            {
                _roleManager = value;
            }
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().Get<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        // GET: Role
        
        public ActionResult Index()
        {
            List<RoleViewModel> list = new List<RoleViewModel>();

            foreach(var role in RoleManager.Roles)
            {
                list.Add(new RoleViewModel(role));
            }
            return View(list);
        }
        [Authorize]
        public ActionResult UpdateUserRole(string UserId)
        {
            List<SelectListItem> RolesList = new List<SelectListItem>();

            foreach (var role in RoleManager.Roles)
            {
                RolesList.Add(new SelectListItem() { Value = role.Name, Text = role.Name });
            }
            ViewBag.Roles = RolesList;
            ViewBag.UserId = UserId;
            return View();
        }
        [HttpPost]
        [Authorize]
        public async Task<ActionResult> UpdateUserRole([Bind(Include = "UserId,Name")] RoleViewModel Role, string UserId)
        {



            var roles = await UserManager.GetRolesAsync(UserId);
            await UserManager.RemoveFromRolesAsync(UserId, roles.ToArray());
           
            
            var result = await UserManager.AddToRoleAsync(UserId, Role.Name);
            List<SelectListItem> RolesList = new List<SelectListItem>();

            foreach (var role in RoleManager.Roles)
            {
                RolesList.Add(new SelectListItem() { Value = role.Name, Text = role.Name });
            }
            ViewBag.Roles = RolesList;

            
            return RedirectToAction("Index", "Manage", new { UserId=UserId});
        }
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Create(RoleViewModel model)
        {
            var role = new ApplicationRole() { Name = model.Name };
            await RoleManager.CreateAsync(role);
            return RedirectToAction("Index");
        }

        public async Task<ActionResult> Edit(string id)
        {
            var role = await RoleManager.FindByIdAsync(id);
            return View(new RoleViewModel(role));
        }

        [HttpPost]
        public async Task<ActionResult> Edit(RoleViewModel model)
        {
            var role = new ApplicationRole() { Id = model.Id, Name = model.Name };
            await RoleManager.UpdateAsync(role);
            return RedirectToAction("Index");
        }

        public async Task<ActionResult> Details(string id)
        {
            var role = await RoleManager.FindByIdAsync(id);
            return View(new RoleViewModel(role));

        }

        public async Task<ActionResult> Delete(string id)
        {
            var role = await RoleManager.FindByIdAsync(id);
            return View(new RoleViewModel(role));

        }

        public async Task<ActionResult> DeleteConfirmed(string id) {
            var role = await RoleManager.FindByIdAsync(id);
            await RoleManager.DeleteAsync(role);
            return RedirectToAction("Index");
        }


    }
}

MovieStore/Views/Shared/PublicMenuNav.cshtml
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="row fixed-nav">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav pull-left admin-section">
                <li>@Html.ActionLink("Admin section", "OpenCart", "ShopingCart",routeValues: new { id = Session["OrderId"] }, htmlAttributes:new { })</li>
            </ul>
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Home", "Index", "Home")</li>
                <li>@Html.ActionLink("About", "About", "Home")</li>
                <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                <li>@Html.ActionLink("Movies", "ShopMovies", "Movies")</li>
            </ul>
            @Html.Partial("_LoginPartial")
            @Html.Action("Cart", "ShopingCart");
        </div>
    </div>
</div>

MovieStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="~/Content/style.css" rel="stylesheet" />

</head>
<body>
    
    @Html.Partial("PublicMenuNav")
    
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")

    @RenderSection("scripts", required: false)
</body>
</html>

MovieStore/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")



    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="~/Content/style.css" rel="stylesheet" />
    <link href="~/Content/AdminStyel.css" rel="stylesheet" />
</head>
<body>
@Html.Partial("PublicMenuNav")

    <nav class="navbar navbar-inverse sidebar" role="navigation">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-sidebar-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand  toggle-btn" href="">Movie Store </a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-sidebar-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="@Url.Action("OpenCart","ShopingCart", new { id=Session["OrderId"]})">See Your Cart<span style="font-size:16px;" class="pull-right hidden-xs showopacity"><i class="fa fa-shopping-cart" aria-hidden="true"></i></span></a></li>
                    <li><a href="@Url.Action("PreviousOrder","Orders")">Previous Purchases<span style="font-size:16px;" class="pull-right hidden-xs showopacity"><i class="fa fa-money" aria-hidden="true"></i></span></a></li>
                    <li><a href="@Url.Action("Index","Manage")">Profile<span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-user"></span></a></li>
                    @if (User.IsInRole("Admin"))
                    {
                    <li><a href="@Url.Action("Chat","Home")">Messages<span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-envelope"></span></a></li>
                    <li class="dropdown">
                        <a href="@Url.Action("Index","Movies")" class="dropdown-toggle" data-toggle="dropdown">Movie <span class="caret"></span><span style="font-size:16px;" class="pull-right hidden-xs showopacity"><i class="fa fa-film" aria-hidden="true"></i></span></a>
                        <ul class="dropdown-menu forAnimate" role="menu">
                            <li><a href="@Url.Action("Create","Movies")">Add</a></li>
                            <li><a href="@Url.Action("Index","Movies")">Manage</a></li>
                        </ul>
                    </li>
                    
                    <li>
                        <a href="@Url.Action("Index", "Orders")" class="dropdown-toggle" >Orders <span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-asterisk"></span> </a>
                    </li>

                    <li>
                        <a href="@Url.Action("Index", "Role")" class="dropdown-toggle">Roles <span style="font-size:16px;" class="pull-right hidden-xs showopacity"><i class="fa fa-users" aria-hidden="true"></i></span> </a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index", "Account")" class="dropdown-toggle">Users <span style="font-size:16px;" class="pull-right hidden-xs showopacity"><i class="fa fa-user-circle" aria-hidden="true"></i></span> </a>
                    </li>

                    <li>
                        <a href="@Url.Action("Index", "Customers")" class="dropdown-toggle">Simple Users <span style="font-size:16px;" class="pull-right hidden-xs showopacity"><i class="fa fa-user-o" aria-hidden="true"></i></span> </a>
                    </li>
                    }
                </ul>
            </div>
        </div>
    </nav>
    <script>

    </script>
    <div class="main">
        @RenderBody()
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")

    @RenderSection("scripts", required: false)
</body>
</html>